from labs03.functions import fib_nierekurencyjnie_error

print(fib_nierekurencyjnie_error(4))
